/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check



//@type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
export default {
  principlesSidebar: [
    'our_mission',
    {
      type: 'category',
      label: 'Principles',
      collapsed: false,
      items: [
        'the_principles/activity',
        'the_principles/nutrition',
        'the_principles/hydration',
        'the_principles/sleep',
      ],
    },
    {
      type: 'category',
      label: 'Insights',
      collapsed: false,
      items: [
        'insights/brain_health',
        'insights/heart_health',
        'insights/weightloss',
        'insights/children_health',
      ],
    },
  ],
};


//const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
//principlesSidebar: [{type: 'autogenerated', dirName: '.',}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ], */
//};

//export default sidebars;
